/**
 * @fileoverview gRPC-Web generated client stub for monitor
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: monitor.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as monitor_pb from './monitor_pb'; // proto import: "monitor.proto"


export class MonitorServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetStats = new grpcWeb.MethodDescriptor(
    '/monitor.MonitorService/GetStats',
    grpcWeb.MethodType.UNARY,
    monitor_pb.StatsRequest,
    monitor_pb.StatsResponse,
    (request: monitor_pb.StatsRequest) => {
      return request.serializeBinary();
    },
    monitor_pb.StatsResponse.deserializeBinary
  );

  getStats(
    request: monitor_pb.StatsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<monitor_pb.StatsResponse>;

  getStats(
    request: monitor_pb.StatsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: monitor_pb.StatsResponse) => void): grpcWeb.ClientReadableStream<monitor_pb.StatsResponse>;

  getStats(
    request: monitor_pb.StatsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: monitor_pb.StatsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.MonitorService/GetStats',
        request,
        metadata || {},
        this.methodDescriptorGetStats,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.MonitorService/GetStats',
    request,
    metadata || {},
    this.methodDescriptorGetStats);
  }

  methodDescriptorStreamStats = new grpcWeb.MethodDescriptor(
    '/monitor.MonitorService/StreamStats',
    grpcWeb.MethodType.SERVER_STREAMING,
    monitor_pb.StatsRequest,
    monitor_pb.StatsResponse,
    (request: monitor_pb.StatsRequest) => {
      return request.serializeBinary();
    },
    monitor_pb.StatsResponse.deserializeBinary
  );

  streamStats(
    request: monitor_pb.StatsRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<monitor_pb.StatsResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/monitor.MonitorService/StreamStats',
      request,
      metadata || {},
      this.methodDescriptorStreamStats);
  }

}

